### ISSUE TITLE
How to train the LSTM network?

### ISSUE THREAD

**Issue by cgoxopx** [artix75/psyc#1]
I need an example.

**Comment by cgoxopx** [comment]
Just like the data  
```
#input         output
0.1 0.2        0.3 0.4    
0.5 0.6        0.7 0.8    
...  
```  
How to use it?

**Comment by artix75** [comment]
All training datasets  must be encoded as an array of doubles. 
In case on recurrent networks (such as LSTM), the dataset layout is the following:

<TOTAL_SEQUENCE_COUNT><SEQ1><SEQ2>.....
 where every SEQ has the following layout:
<SEQUENCE_ITEMS_COUNT><INPUT1><INPUT2>...<TARGET1><TARGET2>...

So, if we use the data you posted as example we would have:

`double data[] = {
    2.0, 
    2.0, 0.1, 0.2, 0.3, 0.4,
    2.0, 0.5, 0.6, 0.7, 0.8
}`

The first number is the total sequences count (in your examples we have two sequences, the first row and the second row).

For every sequence, the first value must be the number of items in the sequence (note that Psych currently requires the same number of inputs and outputs for recurrent networks).
In your example, every sequence (row) has two items (two inputs/outputs).

So we have 2.0 (item count), 0.5, 0.6, 0.7, 0.8 for the first sequence.

As for text-based datasets, there's also a Ruby utility script (text2dataset.rb) that you can find inside the utils/ directory. It can help you convert text data to datasets arrays that you can directly include into your C project in order to be feeded to Psych for training.

I hope that this was helpful to you.

**Comment by cgoxopx** [comment]
Thank you

**Comment by cgoxopx** [comment]
How to predict datas?  By `PSTest`?

**Comment by artix75** [comment]
PSClassify. You can use PSTest on a test dataset (different from training dataset) in order to test the accuracy of your trained NN

**Comment by cgoxopx** [comment]
oh
